### ISSUE TITLE
Update release notes

### ISSUE THREAD

**Issue by toledosq** [sd-webui/stable-diffusion#150]
Suggest adding a section to README.md or adding a changelog to highlight major changes in master. This repo has taken off and the changes are coming so fast it can be difficult to keep up with what each new release is actually doing.

**Comment by altryne** [comment]
@hlky let's move to releases. 

- This way we can make sure that only the tested release will get pushed to main repo (reduce amount of duplicate but reports) 
- We can generate release notes easily (Github interface does this quite simply
- Folks can subscribe to the releases and get notified of new features in advance
