### ISSUE TITLE
img2img masking subtly updates parts of image that are not masked as well

### ISSUE THREAD

**Issue by ddgond** [sd-webui/stable-diffusion#153]
This is more noticeable when chaining multiple changes, but in my use case of keeping a polished face the same, it ends up becoming a blurry smudge within 5 iterations despite not being masked

**Comment by hlky** [comment]
Can't really tell you more without seeing the images, but it could just be that the effect you want needs to be done in a different way. Making it easier to actually do what you want given everything that can affect the output is something me and @altryne are working on.

**Comment by ddgond** [comment]
I bring this up because I was using it yesterday in this way without this issue, and after pulling from the main branch today was being affected by it. I can post example images of what I did yesterday vs today in a bit, and have so far checked that commit [ef36e0a](https://github.com/hlky/stable-diffusion/tree/ef36e0a5db91c9ac3bd50958f2f289443140b612) works as expected (this was the last commit message I remember seeing when I pulled originally).

**Comment by ddgond** [comment]
[Here](https://imgur.com/a/CVjqwWk) you can see my workflow yesterday, where I masked certain parts of the image to change them, but always keeping the face the same (looking at the eyes makes this obvious).
[Here](https://imgur.com/a/Tgpg4fe) is the same workflow after pulling today, again masking the parts I wished to replace. The face is always marked as an area that should not be changed, yet is notably changed by the time you get to the final image, and you can even see changes between individual steps.

**Comment by ddgond** [comment]
I'm working with the earlier commit for now, but this seems like an important issue to bring up when it's such a useful feature.

**Comment by anon-hlhl** [comment]
This is a consequence of my PR. The unmasked portions of the initial image do go through the final sampler pass.

The remedy for this would be to re-apply the mask after the sampling is complete. This is how masking used to work, but I removed in favour of the marginally better edge blending as a result of this final pass.

https://github.com/hlky/stable-diffusion-webui/pull/308/files/ce67b07efda872d607b203c8e0b2e8e2dda9990c..9cb4310a021125ef562efc12630dfe8a22369871#diff-e093b909cce8fa9f0d7a77571607f8a1f9733c18d6e68ca2d03699c962df6fb5

**Comment by anon-hlhl** [comment]
When I originally implemented the inpainting functionality, I was not imagining its use as part of an iterative/loopback process where the lossy behaviour could be amplified with each iteration, and I didn't consider the degredation a significant problem compared to the improvements it provided to inpainting. 

I think perhaps if this is part of a workflow where this degredation is unacceptible, then perhaps Inpainting & Masking should be different functions, or there should be an option to re-apply the unmasked areas verbatim as it previously worked, or this could simply be assumed if the loopback option is selected.

**Comment by 1blackbar** [comment]
yup its a thing, i noticed that too, unmasked stuff should be left intact, its a bug

**Comment by anon-hlhl** [comment]
It was very intentional, see this example, where I masked some cat eyes and asked for a painting:

The inpainting behaviour, where the original masked eyes go through the sampler:
![no-preserve](https://user-images.githubusercontent.com/112447525/187742663-01dc7603-3868-4e4e-a473-aea7e392edd7.png)

Or the inpainting, but with the original preserve behaviour, where the original masked sections are re-applied after sampling:
![preserve](https://user-images.githubusercontent.com/112447525/187742781-00e71c12-bb7f-479f-8236-26bc8aa0351c.png)

Nevertheless, I appreciate everyone likes the choise, so I implemented a toggle here:
https://github.com/anon-hlhl/stable-diffusion-webui/commit/a38dfe252b47d03fd7db06adb314d67527e54df2

I'll await hlky's opinion before I make a PR.

**Comment by anon-hlhl** [comment]
>do you mean to say unmasked here?

Yes, I masked the eyes and selected the "Keep masked area" option. But you're right, it is confusing terminology as one is essentially inverted.

**Comment by ddgond** [comment]
@hlky can we get some clarification on the expected behavior here? In my experience with other software masking does not tend to apply effects partially (or at all) to the masked area, and this current behavior is confusing and limiting.

**Comment by 1blackbar** [comment]
in other words- this should never happen, its a bug

**Comment by thojmr** [comment]
Like others above, I would suggest the default to only affect the masked area.  People are going to expect the mask to ONLY affect the masked area, or the reverse.  Making some hybrid mask logic the default is only going to cause a ton of new issue tickets down the road.

An unfortunate side affect of applying to the while image is blurring of text.  If you image has any text in it.  RIP meme templates.

**Comment by Dawgmastah** [comment]
I can confirm significant arctifacting with this change in masked areas of faces

**Comment by Dawgmastah** [comment]
> It was very intentional, see this example, where I masked some cat eyes and asked for a painting:
> 
> The inpainting behaviour, where the original masked eyes go through the sampler: ![image](https://user-images.githubusercontent.com/112447525/187743349-9951b3db-95dc-41a2-bead-702a5bc577b7.png)
> 
> Or the inpainting, but with the original preserve behaviour, where the original masked sections are re-applied after sampling: ![image](https://user-images.githubusercontent.com/112447525/187743361-727b2f2e-00be-4401-a7d9-75f7a4e459e7.png)
> 
> The second example shows where too much of the original photographic style is preserved, particularly around where the edges blend in, whereas the first example shows the colour and style matching more closely with the regenerated sections. The effect is more noticable when using lower Sampler Steps values, such as when used with euler ancestral.
> 
> Nevertheless, I appreciate everyone likes the choise, so I implemented a toggle here: [anon-hlhl/stable-diffusion-webui@a38dfe2](https://github.com/anon-hlhl/stable-diffusion-webui/commit/a38dfe252b47d03fd7db06adb314d67527e54df2)
> 
> I'll await hlky's opinion before I make a PR.

I tried the code and the behavior remains the same 
(I also don't see a toggle in the UI, I forced in in the code and even forced the AND to execute the new code, and result with artifacted masked faces remains.

Maybe I'm doing something wrong?

**Comment by 1blackbar** [comment]
Yeah sadly the masking and inpainting its not useable at the moment , it makes changes to everything on the image, id use repo before that code was added in but not sure when it happened

**Comment by ddgond** [comment]
@1blackbar I mentioned this earlier but if you `git checkout ef36e0a` you should get a commit with working masking and inpainting.

**Comment by 1blackbar** [comment]
yeh but k euler is so slow now , not sure whats going on with this repo, too many devs at once ?

**Comment by hlky** [comment]
I just ran my [benchmark ](https://github.com/hlky/stable-diffusion/wiki/Benchmarking) for `k_euler` and there is no difference in speed.

**Comment by hlky** [comment]
Update to main. img2img is working with masking, I think the default settings need to changed for cfg scale, and someone mentioned the default mask mode should be "regenerate masked area" as that's what most people are expecting to happen

![Web capture_1-9-2022_145159_127 0 0 1](https://user-images.githubusercontent.com/106811348/187931101-59fbaff2-e7f4-413d-a5d5-d8d6dc2983b6.jpeg)

![00443-50_k_euler_559845130_anime_girl_holding_a_giant_NVIDIA_Tesla_A100_GPU_graphics_card,_Anime_Blu-Ray_boxart,_super_high_deta](https://user-images.githubusercontent.com/106811348/187931147-e446d5d8-5beb-4cce-812f-036a851c0b9f.png)

![00169-50_k_euler_559845130_anime_girl_holding_a_giant_NVIDIA_Tesla_A100_GPU_graphics_card,_Anime_Blu-Ray_boxart,_super_high_deta](https://user-images.githubusercontent.com/106811348/187931228-9051b229-1bf1-4141-b5fc-e61ea5167c38.png)

**Comment by ddgond** [comment]
@hlky I don't think that's the original issue we were talking about (though I do agree that this is more intuitive default behavior for that toggle). Open those two images in separate tabs and switch rapidly between them, and you'll see the entire image gets changed. This causes problems if, for example, you want to change something in the background or a character's clothing, as the face will start to get artifacts.

**Comment by altryne** [comment]
Folks, we hear you, masking should be awesome and work. 
@ddgond have you tried disabling the loopback mechanism?

**Comment by ddgond** [comment]
I am not using the loopback feature, I refeed it back into img2img manually going one step at a time

**Comment by Dawgmastah** [comment]
I understand this new mask might give better results in some cases, but maybe we should separate mask/inpainting? 
Or add a way to pick between a hard mask and a smart one?

Let me illustrate with some pics I made yesterday of a friend where I want him to have a different shirt, a bit of chaged setting and holding a wine glass:

Base image

![160052694_138121522143036_8256540069451018491_n](https://user-images.githubusercontent.com/55219874/187948084-1da7e241-b0d3-4077-bf8d-217d6ce8f8ac.jpg)
![result](https://user-images.githubusercontent.com/55219874/187948088-a2c5fee4-ec07-4005-b436-339a93f6ff7b.png)

Mask

![Mask](https://user-images.githubusercontent.com/55219874/187948162-4d2bfbb4-5b92-48fa-8542-41f124bd4f41.JPG)


Result Before:

![download](https://user-images.githubusercontent.com/55219874/187948191-e0c33b9c-4206-4d1f-a7d5-323941b367ff.png)


But after the new changes this is the result:

![result](https://user-images.githubusercontent.com/55219874/187948326-93a0acd9-572f-4bc2-b6ae-d00a11d3504d.png)


Too many changes (and subtle degradation of the image) on the masked area.

In Images where the subject face is smaller and facing forwards, the effect is greater, with noise, jumbled eyes and noses

example:

![faceDistort](https://user-images.githubusercontent.com/55219874/187949236-a4c14d39-ad8b-4d4f-b205-1bc58e3f82e2.JPG)


(you can reproduce by grabbing a base picture, masking the face and try to modify the scene,

**Comment by Dawgmastah** [comment]
Also..related issue.
When upscaling using the "Upscale images using RealESRGAN" toggle, it will upscale the raw output image without the mask.
Example, if Im using the mask as above, the upscaled image will be a distorted unknown face, not an upscaling of the final image.

**Comment by siriux** [comment]
Maybe an option is to include a parameter to control how much of the image outside of the mask it can affect. Set it to 0 to keep everything outside the mask intact (old behavior), or to something larger to expand and blur a second mask applied only to final diffusion pass (infinity would be equivalent to the new behavior).

Or for better control, we can instead include two parameters, one for expansion and another one for blur. And show this second mask with a different color to allow the user to see what's going to be affected.

This would bring the best of both worlds in a single configurable tool.

**Comment by Dawgmastah** [comment]
@hlky, what are your thoughts on the issue?

This is the only thing keeping me from upgrading to the newest shiny versions, as my workflow heavily uses masking
