### ISSUE TITLE
Failed inference for GFPGAN: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor)

### ISSUE THREAD

**Issue by rupeshs** [sd-webui/stable-diffusion#178]
Getting error on GFPGAN CPU, Windows 10.
webui.py --gfpgan-cpu --esrgan-cpu --optimized

![satble diif](https://user-images.githubusercontent.com/3255994/187727318-775107a5-1a46-4d47-a80f-78497bfc05b0.PNG)

**Comment by rinukkusu** [comment]
Getting the same error, when trying to run it on CPU.
