### ISSUE TITLE
Not able to regenerate exact result from yaml file / some info is missing

### ISSUE THREAD

**Issue by hybridherbst** [sd-webui/stable-diffusion#203]
It seems that in some modes, the result can be 100% regenerated from the yaml:
- variation amount = 0
- batch size = 1
Then I can copy prompt, steps and seed from the YAML and regenerate and continue to iterate on exactly that image.

However, when generating variations with a variation amount, or using batch size =2, that is not possible anymore – the results don't match. This makes it hard / impossible to continue to work on a result.

Maybe the "variation seed" is what's missing from the YAML?

Related to
- #201

**Comment by GatesDA** [comment]
If there's variation then it only keeps the variation seed.  There should be extra fields for variation amount and variation seed in this case.
