### ISSUE TITLE
Aspect ratio box seems to be broken

### ISSUE THREAD

**Issue by JamesIV4** [sd-webui/stable-diffusion#219]
I pulled last night and saw the aspect ratio addition, it was working great and showed what the ratio would be for different image size settings and the showing total pixels was very helpful to find the max my card can handle at 16:9.

I just pulled again today and now it's an editable box that doesn't appear to do anything. The values don't appear after moving the size sliders, and putting a ratio like 1.777 doesn't affect the output.

**Comment by hlky** [comment]
@altryne

**Comment by altryne** [comment]
Yeah, this is on me. Going to add it back today
